import { useState } from "react";
import React from 'react';
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "../components/header.js";
import Search from "@/components/search.js";
import HeroSection from "../components/main.js";

export default function Home() {
  const [searchActive, setSearchActive] = useState(false);

  const handleSearchClick = () => {
    setSearchActive(true);
  };

  return (
    <>
      <Head>
        <title>Etherscan Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
        <Header />
        <Search onSearchClick={handleSearchClick} />
        {searchActive ? null : <HeroSection/>}
      </section>
    </>
  );
}
